### ISSUE TITLE
Could you please introduce a little bit more about this repo?

### ISSUE THREAD

**Issue by Disciple7** [arijitx/Fewshot-Learning-with-BERT#1]
I'm studying about few-shot model on SNIPS-NLU data set, And I think this project may be a good. However, I don't know about which paper this repo depend on. README.md with only one line may be way too simple...
Could you please introduce more about this repo? Like paper citation, or document if you design this yourself.

**Comment by arijitx** [comment]
Hey sorry, I did this as part of a course project and later wrote a paper but that didn't go through, I have updated the readme with the paper. You can find the approach detailed in there.
